export const SYSTEM_PERMISSION_CODES = [
  'dashboard.admin.read',
  'dashboard.client.read',
  'users.read.team',
  'users.read.all',
  'users.create',
  'users.update.team',
  'users.update.all',
  'users.disable',
  'users.assign_manager',
  'users.assign_pricelist',
  'users.super_admin.read',
  'users.super_admin.manage',
  'roles.read',
  'roles.manage',
  'articles.coffins.read',
  'articles.coffins.write',
  'articles.coffins.delete',
  'articles.coffins.import',
  'articles.coffins.upload_image',
  'articles.accessories.read',
  'articles.accessories.write',
  'articles.accessories.delete',
  'articles.accessories.import',
  'articles.marmista.read',
  'articles.marmista.write',
  'articles.marmista.delete',
  'articles.marmista.import',
  'lookups.read',
  'lookups.manage',
  'measures.read',
  'measures.manage',
  'pricelists.sale.read',
  'pricelists.sale.write',
  'pricelists.sale.delete',
  'pricelists.sale.assign',
  'pricelists.sale.preview',
  'pricelists.sale.recalculate',
  'pricelists.purchase.read',
  'pricelists.purchase.write',
  'pricelists.purchase.delete',
  'pricelists.purchase.preview',
  'pricelists.purchase.recalculate',
  'catalog.pdf.read',
  'catalog.pdf.write',
  'client.profile.read',
  'client.password.change',
  'client.catalog.funeral.read',
  'client.catalog.marmista.read',
] as const

export type PermissionCode = (typeof SYSTEM_PERMISSION_CODES)[number]

export interface PermissionDefinition {
  code: PermissionCode
  resource: string
  action: string
  scope?: string
  label: string
  description: string
  isSystem: true
}

export const SYSTEM_PERMISSIONS: PermissionDefinition[] = [
  { code: 'dashboard.admin.read', resource: 'dashboard', action: 'read', scope: 'admin', label: 'Dashboard Admin', description: 'Vedere dashboard e metriche amministrative.', isSystem: true },
  { code: 'dashboard.client.read', resource: 'dashboard', action: 'read', scope: 'client', label: 'Dashboard Cliente', description: 'Vedere dashboard area cliente.', isSystem: true },
  { code: 'users.read.team', resource: 'users', action: 'read', scope: 'team', label: 'Utenti Team', description: 'Vedere gli utenti nel proprio perimetro.', isSystem: true },
  { code: 'users.read.all', resource: 'users', action: 'read', scope: 'all', label: 'Utenti Globali', description: 'Vedere tutti gli utenti non super admin.', isSystem: true },
  { code: 'users.create', resource: 'users', action: 'create', label: 'Crea Utenti', description: 'Creare nuovi utenti.', isSystem: true },
  { code: 'users.update.team', resource: 'users', action: 'update', scope: 'team', label: 'Modifica Utenti Team', description: 'Modificare utenti del proprio perimetro.', isSystem: true },
  { code: 'users.update.all', resource: 'users', action: 'update', scope: 'all', label: 'Modifica Utenti Globali', description: 'Modificare utenti fuori dal proprio team.', isSystem: true },
  { code: 'users.disable', resource: 'users', action: 'disable', label: 'Disattiva Utenti', description: 'Disattivare utenti.', isSystem: true },
  { code: 'users.assign_manager', resource: 'users', action: 'assign_manager', label: 'Assegna Manager', description: 'Assegnare il manager di un utente.', isSystem: true },
  { code: 'users.assign_pricelist', resource: 'users', action: 'assign_pricelist', label: 'Assegna Listino', description: 'Assegnare listini a utenti cliente.', isSystem: true },
  { code: 'users.super_admin.read', resource: 'users', action: 'read', scope: 'super_admin', label: 'Vedi Super Admin', description: 'Vedere utenti super admin.', isSystem: true },
  { code: 'users.super_admin.manage', resource: 'users', action: 'manage', scope: 'super_admin', label: 'Gestisci Super Admin', description: 'Gestire utenti super admin.', isSystem: true },
  { code: 'roles.read', resource: 'roles', action: 'read', label: 'Vedi Ruoli', description: 'Vedere ruoli e permessi.', isSystem: true },
  { code: 'roles.manage', resource: 'roles', action: 'manage', label: 'Gestisci Ruoli', description: 'Creare, modificare o eliminare ruoli custom.', isSystem: true },
  { code: 'articles.coffins.read', resource: 'articles.coffins', action: 'read', label: 'Vedi Cofani', description: 'Vedere articoli cofani.', isSystem: true },
  { code: 'articles.coffins.write', resource: 'articles.coffins', action: 'write', label: 'Modifica Cofani', description: 'Creare e modificare cofani.', isSystem: true },
  { code: 'articles.coffins.delete', resource: 'articles.coffins', action: 'delete', label: 'Elimina Cofani', description: 'Eliminare cofani.', isSystem: true },
  { code: 'articles.coffins.import', resource: 'articles.coffins', action: 'import', label: 'Importa Cofani', description: 'Importare cofani da Excel.', isSystem: true },
  { code: 'articles.coffins.upload_image', resource: 'articles.coffins', action: 'upload_image', label: 'Carica Immagini Cofani', description: 'Caricare immagini per i cofani.', isSystem: true },
  { code: 'articles.accessories.read', resource: 'articles.accessories', action: 'read', label: 'Vedi Accessori', description: 'Vedere articoli accessori.', isSystem: true },
  { code: 'articles.accessories.write', resource: 'articles.accessories', action: 'write', label: 'Modifica Accessori', description: 'Creare e modificare accessori.', isSystem: true },
  { code: 'articles.accessories.delete', resource: 'articles.accessories', action: 'delete', label: 'Elimina Accessori', description: 'Eliminare accessori.', isSystem: true },
  { code: 'articles.accessories.import', resource: 'articles.accessories', action: 'import', label: 'Importa Accessori', description: 'Importare accessori da Excel.', isSystem: true },
  { code: 'articles.marmista.read', resource: 'articles.marmista', action: 'read', label: 'Vedi Articoli Marmista', description: 'Vedere articoli marmista.', isSystem: true },
  { code: 'articles.marmista.write', resource: 'articles.marmista', action: 'write', label: 'Modifica Articoli Marmista', description: 'Creare e modificare articoli marmista.', isSystem: true },
  { code: 'articles.marmista.delete', resource: 'articles.marmista', action: 'delete', label: 'Elimina Articoli Marmista', description: 'Eliminare articoli marmista.', isSystem: true },
  { code: 'articles.marmista.import', resource: 'articles.marmista', action: 'import', label: 'Importa Articoli Marmista', description: 'Importare articoli marmista da Excel.', isSystem: true },
  { code: 'lookups.read', resource: 'lookups', action: 'read', label: 'Vedi Lookup', description: 'Vedere categorie e lookup.', isSystem: true },
  { code: 'lookups.manage', resource: 'lookups', action: 'manage', label: 'Gestisci Lookup', description: 'Creare, modificare o eliminare lookup.', isSystem: true },
  { code: 'measures.read', resource: 'measures', action: 'read', label: 'Vedi Misure', description: 'Vedere misure dei cofani.', isSystem: true },
  { code: 'measures.manage', resource: 'measures', action: 'manage', label: 'Gestisci Misure', description: 'Creare, modificare o eliminare misure.', isSystem: true },
  { code: 'pricelists.sale.read', resource: 'pricelists.sale', action: 'read', label: 'Vedi Listini Vendita', description: 'Vedere listini di vendita.', isSystem: true },
  { code: 'pricelists.sale.write', resource: 'pricelists.sale', action: 'write', label: 'Modifica Listini Vendita', description: 'Creare e modificare listini di vendita.', isSystem: true },
  { code: 'pricelists.sale.delete', resource: 'pricelists.sale', action: 'delete', label: 'Elimina Listini Vendita', description: 'Eliminare listini di vendita.', isSystem: true },
  { code: 'pricelists.sale.assign', resource: 'pricelists.sale', action: 'assign', label: 'Assegna Listini Vendita', description: 'Assegnare listini di vendita agli utenti.', isSystem: true },
  { code: 'pricelists.sale.preview', resource: 'pricelists.sale', action: 'preview', label: 'Anteprima Listini Vendita', description: 'Vedere anteprima prezzi listini di vendita.', isSystem: true },
  { code: 'pricelists.sale.recalculate', resource: 'pricelists.sale', action: 'recalculate', label: 'Ricalcola Listini Vendita', description: 'Rigenerare snapshot prezzi listini di vendita.', isSystem: true },
  { code: 'pricelists.purchase.read', resource: 'pricelists.purchase', action: 'read', label: 'Vedi Listini Acquisto', description: 'Vedere listini di acquisto.', isSystem: true },
  { code: 'pricelists.purchase.write', resource: 'pricelists.purchase', action: 'write', label: 'Modifica Listini Acquisto', description: 'Creare e modificare listini di acquisto.', isSystem: true },
  { code: 'pricelists.purchase.delete', resource: 'pricelists.purchase', action: 'delete', label: 'Elimina Listini Acquisto', description: 'Eliminare listini di acquisto.', isSystem: true },
  { code: 'pricelists.purchase.preview', resource: 'pricelists.purchase', action: 'preview', label: 'Anteprima Listini Acquisto', description: 'Vedere anteprima prezzi listini di acquisto.', isSystem: true },
  { code: 'pricelists.purchase.recalculate', resource: 'pricelists.purchase', action: 'recalculate', label: 'Ricalcola Listini Acquisto', description: 'Rigenerare snapshot prezzi listini di acquisto.', isSystem: true },
  { code: 'catalog.pdf.read', resource: 'catalog.pdf', action: 'read', label: 'Vedi Catalogo PDF', description: 'Vedere stato e metadati del catalogo PDF.', isSystem: true },
  { code: 'catalog.pdf.write', resource: 'catalog.pdf', action: 'write', label: 'Modifica Catalogo PDF', description: 'Caricare o sostituire il catalogo PDF.', isSystem: true },
  { code: 'client.profile.read', resource: 'client.profile', action: 'read', label: 'Vedi Profilo Cliente', description: 'Vedere il profilo cliente e i listini collegati.', isSystem: true },
  { code: 'client.password.change', resource: 'client.password', action: 'change', label: 'Cambia Password Cliente', description: 'Cambiare la propria password.', isSystem: true },
  { code: 'client.catalog.funeral.read', resource: 'client.catalog.funeral', action: 'read', label: 'Vedi Catalogo Funebre Cliente', description: 'Consultare il catalogo funebre assegnato.', isSystem: true },
  { code: 'client.catalog.marmista.read', resource: 'client.catalog.marmista', action: 'read', label: 'Vedi Catalogo Marmista Cliente', description: 'Consultare il catalogo marmista assegnato.', isSystem: true },
]
