import type { PermissionCode } from './permissions'

export type SystemRoleName =
  | 'super_admin'
  | 'manager'
  | 'collaboratore'
  | 'impresario_funebre'
  | 'marmista'

export const SYSTEM_ROLE_DEFAULTS: Record<SystemRoleName, PermissionCode[]> = {
  super_admin: [
    'dashboard.admin.read',
    'users.read.team',
    'users.read.all',
    'users.create',
    'users.update.team',
    'users.update.all',
    'users.disable',
    'users.assign_manager',
    'users.assign_pricelist',
    'users.super_admin.read',
    'users.super_admin.manage',
    'roles.read',
    'roles.manage',
    'articles.coffins.read',
    'articles.coffins.write',
    'articles.coffins.delete',
    'articles.coffins.import',
    'articles.coffins.upload_image',
    'articles.accessories.read',
    'articles.accessories.write',
    'articles.accessories.delete',
    'articles.accessories.import',
    'articles.marmista.read',
    'articles.marmista.write',
    'articles.marmista.delete',
    'articles.marmista.import',
    'lookups.read',
    'lookups.manage',
    'measures.read',
    'measures.manage',
    'pricelists.sale.read',
    'pricelists.sale.write',
    'pricelists.sale.delete',
    'pricelists.sale.assign',
    'pricelists.sale.preview',
    'pricelists.sale.recalculate',
    'pricelists.purchase.read',
    'pricelists.purchase.write',
    'pricelists.purchase.delete',
    'pricelists.purchase.preview',
    'pricelists.purchase.recalculate',
    'catalog.pdf.read',
    'catalog.pdf.write',
  ],
  manager: [
    'dashboard.admin.read',
    'users.read.team',
    'users.read.all',
    'users.create',
    'users.update.team',
    'users.update.all',
    'users.disable',
    'users.assign_manager',
    'users.assign_pricelist',
    'articles.coffins.read',
    'articles.coffins.write',
    'articles.coffins.delete',
    'articles.coffins.import',
    'articles.coffins.upload_image',
    'articles.accessories.read',
    'articles.accessories.write',
    'articles.accessories.delete',
    'articles.accessories.import',
    'articles.marmista.read',
    'articles.marmista.write',
    'articles.marmista.delete',
    'articles.marmista.import',
    'lookups.read',
    'lookups.manage',
    'measures.read',
    'measures.manage',
    'pricelists.sale.read',
    'pricelists.sale.write',
    'pricelists.sale.delete',
    'pricelists.sale.assign',
    'pricelists.sale.preview',
    'pricelists.sale.recalculate',
    'pricelists.purchase.read',
    'pricelists.purchase.write',
    'pricelists.purchase.delete',
    'pricelists.purchase.preview',
    'pricelists.purchase.recalculate',
    'catalog.pdf.read',
    'catalog.pdf.write',
  ],
  collaboratore: [
    'dashboard.admin.read',
    'users.read.team',
    'users.update.team',
    'articles.coffins.read',
    'articles.coffins.write',
    'articles.coffins.import',
    'articles.coffins.upload_image',
    'articles.accessories.read',
    'articles.accessories.write',
    'articles.accessories.import',
    'articles.marmista.read',
    'articles.marmista.write',
    'articles.marmista.import',
    'lookups.read',
    'measures.read',
  ],
  impresario_funebre: [
    'dashboard.client.read',
    'client.profile.read',
    'client.password.change',
    'client.catalog.funeral.read',
  ],
  marmista: [
    'dashboard.client.read',
    'client.profile.read',
    'client.password.change',
    'client.catalog.marmista.read',
  ],
}
