export const MULTIPART_MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
export const MULTIPART_MAX_FILE_SIZE_MB = MULTIPART_MAX_FILE_SIZE_BYTES / (1024 * 1024)

export const MULTIPART_OPTIONS = {
  limits: {
    fileSize: MULTIPART_MAX_FILE_SIZE_BYTES,
  },
} as const

export const PDF_MAX_FILE_SIZE_BYTES = 300 * 1024 * 1024   // 300 MB
export const PDF_MAX_FILE_SIZE_MB = PDF_MAX_FILE_SIZE_BYTES / (1024 * 1024)
