import type { CoffinItem, AccessoryItem, MarmistaItem, CeabisItem } from './types'

export const mockCoffins: CoffinItem[] = [
  {
    id: 'mock-c1',
    code: 'MR-204-EX',
    description: 'Cofano Impero Oro',
    notes: 'Noce Nazionale, finitura a cera, intagli a mano',
    categories: ['Cofani'],
    subcategories: ['Legni Pregiati'],
    essences: ['Noce Nazionale'],
    figures: ['Classico'],
    colors: ['Naturale'],
    finishes: ['Cera'],
    internalMeasures: {
      headWidth: 58,
      feetWidth: 42,
      shoulderWidth: 58,
      height: 60,
      width: 58,
      depth: 195,
    },
  },
  {
    id: 'mock-c2',
    code: 'MR-312-AB',
    description: 'Cofano Rinascimento',
    notes: 'Ciliegio massello, finitura lucida, decori dorati',
    categories: ['Cofani'],
    subcategories: ['Legni Pregiati'],
    essences: ['Ciliegio'],
    figures: ['Barocco'],
    colors: ['Ciliegio'],
    finishes: ['Lucida'],
    internalMeasures: {
      headWidth: 60,
      feetWidth: 44,
      shoulderWidth: 60,
      height: 62,
      width: 60,
      depth: 198,
    },
  },
  {
    id: 'mock-c3',
    code: 'MR-118-EC',
    description: 'Cofano Semplicità Bianco',
    notes: 'Abete verniciato bianco opaco, linee essenziali',
    categories: ['Cofani'],
    subcategories: ['Economici'],
    essences: ['Abete'],
    figures: ['Moderno'],
    colors: ['Bianco'],
    finishes: ['Opaca'],
    internalMeasures: {
      headWidth: 56,
      feetWidth: 40,
      shoulderWidth: 56,
      height: 58,
      width: 56,
      depth: 192,
    },
  },
  {
    id: 'mock-c4',
    code: 'MR-445-PN',
    description: 'Cofano Eleganza Ebano',
    notes: 'Noce tinto ebano, coperchio bombato, maniglie cromate',
    categories: ['Cofani'],
    subcategories: ['Legni Pregiati'],
    essences: ['Noce Nazionale'],
    figures: ['Classico'],
    colors: ['Ebano'],
    finishes: ['Lucida'],
    internalMeasures: {
      headWidth: 59,
      feetWidth: 43,
      shoulderWidth: 59,
      height: 61,
      width: 59,
      depth: 196,
    },
  },
]

export const mockAccessories: AccessoryItem[] = [
  {
    id: 'mock-a1',
    code: 'ACC-001-CR',
    description: 'Crocifisso in bronzo dorato',
    notes: 'Dimensioni 30x15 cm, finitura dorata anticata',
    categories: ['Crocifissi'],
    pdfPage: 12,
  },
  {
    id: 'mock-a2',
    code: 'ACC-023-MN',
    description: 'Maniglie classiche ottone',
    notes: 'Set da 6 pezzi, peso 1,2 kg cadauna, foro passo 215 mm',
    categories: ['Maniglie'],
    pdfPage: 28,
  },
  {
    id: 'mock-a3',
    code: 'ACC-047-PL',
    description: 'Placca angolare in plastica avorio',
    notes: 'Set da 4 angolari, compatibili con cofani standard',
    categories: ['Accessori Plastica'],
    pdfPage: 45,
  },
  {
    id: 'mock-a4',
    code: 'ACC-089-TN',
    description: 'Targa in ottone incidibile',
    notes: 'Dimensioni 20x8 cm, fissaggio a vite incluso',
    categories: ['Targhe'],
    pdfPage: 67,
  },
]

export const mockMarmista: MarmistaItem[] = [
  {
    id: 'mock-m1',
    code: 'MAR-101-GR',
    description: 'Granito Rosa Sardo lucidato',
    notes: 'Lastra 60x30x3 cm, estratto cave Sardegna',
    publicPrice: 48.50,
    categories: ['Graniti'],
    pdfPage: 5,
  },
  {
    id: 'mock-m2',
    code: 'MAR-215-MB',
    description: 'Marmo Bianco Carrara Classe A',
    notes: 'Lastra 60x30x2 cm, vena grigia fine',
    publicPrice: 72.00,
    categories: ['Marmi'],
    pdfPage: 11,
  },
  {
    id: 'mock-m3',
    code: 'MAR-330-BS',
    description: 'Basalto Nero Sardegna',
    notes: 'Lastra 50x25x4 cm, superficie fiammata',
    publicPrice: 55.80,
    categories: ['Basalti'],
    pdfPage: 19,
  },
  {
    id: 'mock-m4',
    code: 'MAR-442-TR',
    description: 'Travertino Romano Anticato',
    notes: 'Lastra 60x40x3 cm, finitura bocciardata',
    publicPrice: 38.20,
    categories: ['Travertini'],
    pdfPage: 25,
  },
]

export const mockCeabis: CeabisItem[] = [
  {
    id: 'mock-cb1',
    code: 'CEA-011-VC',
    description: 'Vestiti da cerimonia adulto blu navy',
    notes: 'Taglia unica regolabile, tessuto misto poliestere',
    categories: ['Abbigliamento'],
    pdfPage: 3,
  },
  {
    id: 'mock-cb2',
    code: 'CEA-034-LZ',
    description: 'Lenzuolo funebre bianco ricamato',
    notes: 'Cotone 100%, dimensioni 200x90 cm, ricamo croce',
    categories: ['Biancheria'],
    pdfPage: 14,
  },
  {
    id: 'mock-cb3',
    code: 'CEA-056-CS',
    description: 'Cuscino funebre seta avorio',
    notes: 'Dimensioni 45x30 cm, imbottitura poliestere',
    categories: ['Accessori Interni'],
    pdfPage: 22,
  },
  {
    id: 'mock-cb4',
    code: 'CEA-078-FI',
    description: 'Frange decorative oro per bara',
    notes: 'Rotolo 10 mt, larghezza 5 cm, tono oro',
    categories: ['Decorazioni'],
    pdfPage: 31,
  },
]
